#
#  MIT License
#
#  Copyright (c) 2019-2021 ugrong@163.com
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#

server:
  port: 8083

spring:
  redis:
    #password: root
    host: 127.0.0.1
    port: 6379
    timeout: 3600ms

  datasource:
    url: jdbc:mysql://localhost:3306/stock?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml

# 加密配置
encryption:
  # 加密密钥（生产环境建议从环境变量获取）
  secret-key: "MySecretKey123456789012345678901"
  # 是否启用加密
  enabled: true
  # 加密算法
  algorithm: "AES"
  # 加密模式
  mode: "GCM"

# 数据目录配置
data:
  # 数据存储根目录
  # Windows: D:\1stock
  # Linux: /opt/stock
  root-path: ${DATA_ROOT_PATH:D:/1stock}
  # 临时文件目录
  temp-path: ${DATA_TEMP_PATH:${java.io.tmpdir}}

# 缓存配置
cache:
  # 是否启用缓存
  enabled: ${CACHE_ENABLED:false}
  # 默认缓存时间（秒）
  default-ttl: ${CACHE_DEFAULT_TTL:5}
  # 股票数据缓存时间（秒）
  stock-data-ttl: ${CACHE_STOCK_DATA_TTL:5}
  # 热门数据缓存时间（秒）
  hot-data-ttl: ${CACHE_HOT_DATA_TTL:180}
  # 实时数据缓存时间（秒）
  realtime-data-ttl: ${CACHE_REALTIME_DATA_TTL:60}
  # 统计数据缓存时间（秒）
  statistics-data-ttl: ${CACHE_STATISTICS_DATA_TTL:600}
  # 缓存键前缀
  key-prefix: ${CACHE_KEY_PREFIX:stock:}
  # 是否启用缓存预热
  preload-enabled: ${CACHE_PRELOAD_ENABLED:false}
  # 缓存预热时间间隔（秒）
  preload-interval: ${CACHE_PRELOAD_INTERVAL:3600}

# 安全配置
security:
  # JWT配置
#  jwt:
#    secret: ${JWT_SECRET:MySecretKey123456789012345678901234567890}
#    expiration: ${JWT_EXPIRATION:86400}  # 24小时
#    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800}  # 7天
  
  # 重放攻击防护配置
  replay-attack:
    secret-key: ${REPLAY_ATTACK_SECRET_KEY:defaultSecretKey}
    window: ${REPLAY_ATTACK_WINDOW:300000}  # 5分钟
    expire-time: ${REPLAY_ATTACK_EXPIRE_TIME:600000}  # 10分钟
  
  # 限流配置
  rate-limit:
    default-capacity: ${RATE_LIMIT_DEFAULT_CAPACITY:100}
    default-refill-tokens: ${RATE_LIMIT_DEFAULT_REFILL_TOKENS:10}
    default-refill-duration: ${RATE_LIMIT_DEFAULT_REFILL_DURATION:60000}  # 1分钟
    api-capacity: ${RATE_LIMIT_API_CAPACITY:1000}
    api-refill-tokens: ${RATE_LIMIT_API_REFILL_TOKENS:100}
    api-refill-duration: ${RATE_LIMIT_API_REFILL_DURATION:60000}  # 1分钟
    login-capacity: ${RATE_LIMIT_LOGIN_CAPACITY:5}
    login-refill-tokens: ${RATE_LIMIT_LOGIN_REFILL_TOKENS:1}
    login-refill-duration: ${RATE_LIMIT_LOGIN_REFILL_DURATION:60000}  # 1分钟
  
  # XSS防护配置
  xss:
    enabled: ${XSS_PROTECTION_ENABLED:true}
    log-attacks: ${XSS_LOG_ATTACKS:true}
    block-attacks: ${XSS_BLOCK_ATTACKS:true}
  
  # SQL注入防护配置
  sql-injection:
    enabled: ${SQL_INJECTION_PROTECTION_ENABLED:true}
    log-attacks: ${SQL_INJECTION_LOG_ATTACKS:true}
    block-attacks: ${SQL_INJECTION_BLOCK_ATTACKS:true}
  
  # CSRF防护配置
  csrf:
    enabled: ${CSRF_PROTECTION_ENABLED:true}
    token-expire-time: ${CSRF_TOKEN_EXPIRE_TIME:1800000}  # 30分钟

# 日志配置
logging:
  level:
    com.lin.security: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/security.log
    max-size: 100MB
    max-history: 30


